import './globals.css'
import { Inter } from 'next/font/google'
import ThemeRegistry from '@/components/Theme/ThemeRegistry/ThemeRegistry';
import NextAuthProvider from '@/components/Auth/NextAuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Katchau',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ThemeRegistry>
            {children}
          </ThemeRegistry>
        </NextAuthProvider>
      </body>
    </html>
  )
}
