import './globals.css';
import React from 'react';
import { Inter } from 'next/font/google';
import ThemeRegistry from '@/components/Theme/ThemeRegistry/ThemeRegistry';
import NextAuthProvider from '@/components/Auth/NextAuthProvider';
import LocalizationProvider from '@/components/LocalizationProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Katchau',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {

	return (
		<html lang='en'>
			<body className={inter.className}>
				<React.Suspense>
					{/* @ts-expect-error Server Component */}
					<LocalizationProvider>
						<NextAuthProvider>
							<ThemeRegistry>{children}</ThemeRegistry>
						</NextAuthProvider>
					</LocalizationProvider>
				</React.Suspense>
			</body>
		</html>
	);
}
