'use client';

import NextAuthProvider from '@/components/Auth/NextAuthProvider';
import ThemeRegistry from '@/components/Theme/ThemeRegistry/ThemeRegistry';
import LocalizationProvider from '@/lib/intl/components/LocalizationProvider';
import toPseudoLocale from '@/lib/intl/utils/toPseudoLocale';
import ZodSchemaProvider from '@/lib/zod/components/ZodSchemaProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider as MuiLocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import React from 'react';
import './globals.css';

const roboto = Roboto({
	weight: ['300', '400', '500', '700'],
	display: 'swap',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Katchau',
	description: 'Generated by create next app',
};

export default function RootLayout({
	params: { locale },
	children,
}: {
	params: { locale: string };
	children: React.ReactNode;
}) {
	const loc = toPseudoLocale(locale, 'en');

	return (
		<html lang={loc}>
			<body className={roboto.className}>
				<React.Suspense>
					{/* @ts-expect-error Server Component */}
					<LocalizationProvider>
						<MuiLocalizationProvider dateAdapter={AdapterDayjs}>
							<ZodSchemaProvider>
								<NextAuthProvider>
									<ThemeRegistry>{children}</ThemeRegistry>
								</NextAuthProvider>
							</ZodSchemaProvider>
						</MuiLocalizationProvider>
					</LocalizationProvider>
				</React.Suspense>
			</body>
		</html>
	);
}
