name: Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [release]

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: 'Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.cache/Cypress
            ${{ github.workspace }}/.next
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-preview-
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

  UnitTests:
    runs-on: ubuntu-latest
    environment: Preview
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.cache/Cypress
            ${{ github.workspace }}/.next
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-preview-
      - name: Unit tests
        run: npm run test

  E2ETests:
    runs-on: ubuntu-latest
    environment: Preview
    needs: Build
    env:
      NODE_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.cache/Cypress
            ${{ github.workspace }}/.next
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-preview-
      - name: Build test database
        run: npm run test:db:start
      - uses: supabase/setup-cli@v1
        with:
          version: 1.83.7
      - name: Start Supabase
        run: supabase init && supabase start
      - name: Run E2E test suit
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          browser: chrome

  Deploy:
    runs-on: ubuntu-latest
    environment: Preview
    needs: UnitTests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.cache/Cypress
            ${{ github.workspace }}/.next
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-preview-
      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
