name: Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [release]

jobs:
  Install:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install
        run: npm ci
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-preview-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-preview-

  Build:
    runs-on: ubuntu-latest
    environment: Preview
    needs: Install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Restore NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-preview-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-preview-
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-preview-

  Tests:
    runs-on: ubuntu-latest
    environment: Preview
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Restore NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-preview-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-preview-
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-preview-
      - name: Unit tests
        run: npm run test

  Deploy:
    runs-on: ubuntu-latest
    environment: Preview
    needs: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Restore NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-preview-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-preview-
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-preview-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-preview-
      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
