name: Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main]

jobs:
  Install:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-prod-

  Build:
    runs-on: ubuntu-latest
    environment: Production
    needs: Install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Restore NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-prod-
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-prod-

  Migrate:
    runs-on: ubuntu-latest
    environment: Production
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Restore NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-prod-
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-prod-
      - name: Deploy Migration
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  Tests:
    runs-on: ubuntu-latest
    environment: Production
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Restore NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-prod-
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-prod-
      - name: Unit tests
        run: npm run test

  Deploy:
    runs-on: ubuntu-latest
    environment: Production
    needs: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Restore NPM
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-prod-
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Restore Cache Build'
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.vercel/output
          key: ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-prod-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-prod-
      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
